name: Deployment

env:
  APP_CONFIG_ENVIRONMENT: 'production'
  APP_CONFIG_DEPLOY_KEY: ${{ secrets.deploy_key }}

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-22.04
    environment:
      name: production
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Configure app
        run: composer configure-app

      - name: Upload to server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            vendor/**/tests/**
            vendor/**/test/**
            vendor/**/composer.json
            vendor/**/composer.lock

      - name: Call post deploy endpoint
        run: "curl -X POST -H \"Cache-Control: no-cache\" -H \"Authorization: ${{ secrets.deploy_key }}\" https://${{ secrets.domain }}/.deploy"